version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '4623:4623'
    volumes:
      - .:/usr/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
